[versions]
agp = "8.1.4"
org-jetbrains-kotlin-android = "1.9.21"
org-jetbrains-kotlin-jvm = "1.9.0"
ksp = "1.9.21-1.0.15"
libxposed-api = "100"
libxposed-service = "100-1.0.0"

[libraries]
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed-api" }
libxposed-service = { module = "io.github.libxposed:service", version.ref = "libxposed-service" }


[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]

